### ISSUE TITLE
Key warning does not work with threading macros

### ISSUE THREAD

**Issue by chrisetheridge** [pitch-io/uix#100]
**Describe the bug**
Using thread last makes the key warning linter report false-positive key warnings.

**Include minimal repro**
```clojure
(defui bar [props])

(defui foo [props]
  (for [i (range 10)]
    (->> {:key (str "bar-" i )
          :i   i}
         ($ bar))))
```

This will produce a key warning, even though we have provided it as part of the props.

**Expected behavior**
No key warning 😄 . This is not a huge problem, however.

**Additional context**
Possibly related, but if you do `->` instead of `->>` you get 2 warnings. One warning is the key warning, and the other is:

```
------ WARNING #3 - :undeclared-var --------------------------------------------
 File: /Users/chrise/code/cognician/monorepo/src/cognician/activate/view/wizard/audiences.cljc:223:9
--------------------------------------------------------------------------------
 220 |   (for [i (range 10)]
 221 |     (-> {:key (str "bar-" i )
 222 |          :i   i}
 223 |         ($ bar))))
---------------^----------------------------------------------------------------
 Use of undeclared Var cognician.activate.view.wizard.audiences/js
--------------------------------------------------------------------------------
```

**Comment by roman01la** [comment]
@chrisetheridge nice catch! It's definitely a bug. I'm not sure if such case with threading macros should be detected or simply ignored, unless it adds more complexity to linter code. Feel free to investigate.

**Comment by chrisetheridge** [comment]
Cool! I'll dig in. I think it may make the linter code a bit complex to cover all possible permutations, but I'll see
