### ISSUE TITLE
use-subscribe doesn't cleanup re-frame subscriptions

### ISSUE THREAD

**Issue by roman01la** [pitch-io/uix#109]
## Original bug report from Clojurians Slack
> quick question about the use-subscribe hook described in the docs for re-frame interop - I have a subscription that does some cpu intensive logic, but when the component with the use-subscribe hook is unmounted, the subscription continues to execute. Is this expected and can I do anything about it? I'm guessing the watcher on the app-db is not being removed when the component is unmounted, but I don't feel I know enough about how this stuff works to know where to look

> Does it mean that when there’s no active instance of the subscription in UI tree, it’s still being executed?
> — yes

## Debugging
> The thing is, it calls twice the function that subscribes a component to re-frame subscription, but doesn’t cleanup the first subscription.

**Comment by roman01la** [comment]
@green-coder do you have a repro to prove that?

**Comment by green-coder** [comment]
Yes I have, I can provide it tomorrow, but I will still need to explain a bit so here is why:

1. `temp-ref` is instantiated in `ratom/make-reaction`, called from `ratom/run-in-reaction`. It is not a global value, a new instance is created each time the old one is used. It means that it is ok to dispose it.
2. When it is disposed, it removes itself from the ratoms and reactions it was watching.
3. When a reaction passes from at least 1 watcher to 0, it disposes itself, ... and so on upstream.

If you uncomment the 2 lines in the snippet and you test when ref is a reaction, you will see "ref was disposed" and then "temp-ref was disposed".

This will also work when ref is a tracker, its cached reaction will be released. I verified that by counting the reactions created minus the reactions disposed and I had a consistent `1` each time all my views which were using `use-subscription` were not rendered. That `1` is coming from `reagent.atom/temp-reaction` which always point on an instantiated reaction to be used later.

**Comment by green-coder** [comment]
I pushed a test project at https://github.com/green-coder/-better-uix-cleanup-ref

**Comment by roman01la** [comment]
@green-coder I'm not sure I understand what's the problem here. Is it a memory leak or something is not working correctly? Or is it about `temp-ref` not being disposed?

**Comment by green-coder** [comment]
Currently there is no memory leak but `temp-ref` is not disposed in the proper way, source code wise.

The current code assumes that ref is a `Reaction` (i.e. that it implements `cljs.core/IWatchable`), it is not generic and won't work for example when ref is a `Tracker`.

There is also no need to run `.filter` on `.-watching` because:
- in this case there is only 1 element in the list
- n the general case everything in this list should be unwatched, which is what calling `(dispose! temp-ref)` does.

**Comment by roman01la** [comment]
Ok, so the user facing issue is that the code only works with Reaction type
