### ISSUE TITLE
Multiple children don't work in SSR

### ISSUE THREAD

**Issue by chrisetheridge** [pitch-io/uix#124]
**Describe the bug**
SSR crashes when using multiple children for a component. The same code works fine in `cljs` / React, but not in SSR. The exception:

```
Execution error (IllegalArgumentException) at uix.dom.server/render-component! (server.clj:484).
Key must be integer
```

**Include minimal repro**
```clojure
(defui button-row [{:keys [children]}]
  ($ :div.buttons
    children))

(defui button [{:keys [label]}]
  ($ :button.button label))

(defui my-profile []
  ($ button-row
    ($ button {:label "Save Changes"})
    ($ button {:label "Discard Changes"})))

(uix.dom.server/render-to-static-markup ($ my-profile))
```

This fails due to `button-row` receiving multiple children, that aren't wrapped in another `div` or Fragment.

**Expected behavior**
No exception is thrown when writing components like this. According to React docs and tutorials there isn't anything wrong with not wrapping the children in Fragments.

**Comment by roman01la** [comment]
Fixed

**Comment by chrisetheridge** [comment]
Thank you so much!
