### ISSUE TITLE
Ability to configure/replace react/createElement

### ISSUE THREAD

**Issue by cj-price** [pitch-io/uix#136]
**Is your feature request related to a problem? Please describe.**
I would like to use [:css](https://emotion.sh/docs/css-prop) within my uix components. 

**Describe the solution you'd like**
Allow the user to do something like this:
```clojure
(reset! *react-create-element-fn* emotion/jsx)
```
-or-
```clojure
(uix.dom/render-root ($ app) root {:react-create-element-fn emotion/jsx})
```

**Describe alternatives you've considered**
I am not sure if shadow-cljs has the ability to redef react/createElement but that is something I would like to look into.

**Additional context**
Reagent's compiler allows you to do this: https://github.com/reagent-project/reagent/blob/7d8cdad9037ce952ba18868e9a5eaf3fd1c8023e/examples/emotion/src/example/compiler.cljs#L35

**Comment by roman01la** [comment]
There are multiple options. You can do `(set! react/createElement your-create-element)` or create a wrapper macro for `$` macro.
