### ISSUE TITLE
Global State Management

### ISSUE THREAD

**Issue by rawadassaf1** [pitch-io/uix#153]
**Is your feature request related to a problem? Please describe.**
The feature is related to the recurring need of managing global State in the UI. 

**Describe the solution you'd like**
Have the possibility to use global State management libraries like redux in JS or reframe in CLJS one

**Describe alternatives you've considered**
Nothing at this stage

**Additional context**

**Comment by roman01la** [comment]
re-frame is supported by UIx, have a look at docs
