### ISSUE TITLE
How to use :hover selector with tailwindcss

### ISSUE THREAD

**Issue by Fover23** [pitch-io/uix#189]
**Describe the bug**

It not be a bug , I do not know it.😂

`

    (defui right-table []

      ($ :div.grow.overflow-x-auto ($ :table.table 

                                  ($ :thead ($ :tr ($ :th "No.") ($ :th "Name") ($ :th "Job") ($ :th "Favorite Color")))

                                  ($ :tr  ($ :td "1") ($ :td "John Doe") ($ :td "Developer") ($ :td "Blue"))

                                  ($ :tr ($ :td "2") ($ :td "Jane Doe") ($ :td "Designer") ($ :td "Green"))

                                  ($ :tr ($ :td "3") ($ :td "John Smith") ($ :td "Manager") ($ :td "Red")))))`

So, I went mouse hover some tr it will change the background color.

just like this 

`
;; This code not working

 ($ :tr :hover:bg-base-100)`

How to write it ?

**Comment by pragyanatvade** [comment]
You can just use class to do it. 

```
($ :tr {:class "hover:bg-base-100"})
```

**Comment by roman01la** [comment]
The above answer is correct. What's not a valid Clojure keyword can be expressed as a string and passed as `:class` prop.
