### ISSUE TITLE
ratom/Track doesn't work with use-reaction

### ISSUE THREAD

**Issue by roman01la** [pitch-io/uix#199]
Following up on this discussion https://github.com/pitch-io/uix/issues/109#issuecomment-2554629873 cc @green-coder

tl;dr using `ratom/Track` object with `use-reaction` will crash when disposing the object

**Comment by roman01la** [comment]
@green-coder

replacing
```clojure
(defn- cleanup-ref [ref]
  (when-let [^ratom/Reaction temp-ref (aget ref "__rat")]
    (remove-watch ref temp-ref)
    (when-let [watching (.-watching temp-ref)]
      (set! (.-watching temp-ref)
            (.filter watching #(not (identical? ref %)))))))
```

with
```clojure
(defn- cleanup-ref [ref]
  (when-let [^ratom/Reaction temp-ref (aget ref "__rat")]
    (ratom/dispose! temp-ref)))
```

breaks the following behaviour
1. Subscribe UI component to a ratom
2. Update ratom state
3. Unmount the component
4. Mount the component back
5. Update ratom state
6. The update does not trigger UI component update anymore

**Comment by green-coder** [comment]
Aouch 😭 

Thank you for the feedback and sorry that it doesn't work. I should have done more tests on my own. I will take a closer look and try to understand the reason why it's not working.

**Comment by roman01la** [comment]
Yeah I think in general the part about reactions handling in the hook could be improved, but I’m not very good at Reagent internals to understand how to do things properly
