### ISSUE TITLE
clj-kondo exported config

### ISSUE THREAD

**Issue by borkdude** [pitch-io/uix#76]
As discussed here: https://twitter.com/roman01la/status/1542854258235740160

I'd be happy to contribute this.

**Comment by roman01la** [comment]
Is there any input you need in order to create clj-kondo rules for UIx? I guess we could also pull them from [Helix](https://github.com/lilactown/helix/tree/master/resources/clj-kondo.exports/lilactown/helix)?

**Comment by borkdude** [comment]
@roman01la If all macros with non-standard syntax are fully covered in the tests, we can try to make linting work using those examples. Haven't looked at helix, but this library is similar, we could re-use that.

**Comment by roman01la** [comment]
I think clj-kondo could check at least the following two forms:
1. `uix.core/defui` as `clojure.core/defn`
2. `uix.core/$` should have the following signature `($ string-or-symbol ...any)`

**Comment by borkdude** [comment]
Cool. And the keyword is an alias for a function?

**Comment by borkdude** [comment]
Sorry I haven't followed up here.
