### ISSUE TITLE
Linting breaks when using subscribe named function call in defui

### ISSUE THREAD

**Issue by chrisetheridge** [pitch-io/uix#90]
**Describe the bug**
When using `subscribe` as a function name in `defui` component, I get a `NullPointerException` during macro expansion. This only seems to happen on the JVM.

If I remove the re-frame linting in `uix.linter`, then macro expansion works again.

**Include minimal repro**
This fails for me on UIx 0.8.1, when compiling via nrepl on the JVM.

```clojure
(defn subscribe [ref]
  ref)

(defonce *state (atom 1))

(defui foo [a]
  (let [v (subscribe *state)]
    ($ :p a v)))
```

**Expected behavior**
We should be able to use the `subscribe` function name in `defui` on the JVM.

**Additional context**
We don't use re-frame anywhere, but this is own our subscribe implementation.

**Comment by chrisetheridge** [comment]
Please let me know if I can add any additional context 😄

**Comment by chrisetheridge** [comment]
We can work around this by renaming `subscribe` to `subscribe-to`, so its not a huge blocker.

**Comment by roman01la** [comment]
@chrisetheridge What's the error? I guess it might be related to cljs analyzer stuff being called under the hood in re-frame linter. If that's the case, I'm fine to disable re-frame linting when the code runs on JVM.

> We should be able to use the subscribe function

Is it a generic `subscribe` function? Because by default the linter should be looking only at `re-frame.core/subscribe`.

**Comment by chrisetheridge** [comment]
Its a generic subscribe function, yep!

I will reproduce now, but iirc it was a NullPointer coming from the `resolve-var` call [here](https://github.com/pitch-io/uix/blob/master/core/src/uix/linter.clj#L264)

**Comment by chrisetheridge** [comment]
```
Unexpected error (NullPointerException) macroexpanding defui at (src/cognician/dev/web/view/user.cljc:66:1).
null
```

This is all the JVM gives us 😄

**Comment by roman01la** [comment]
Ah, I see. There's `rf-subscribe-call?` that precedes resolving call, the function collects all `subscribe` symbols and then the analyzer tries to to figure out where they are coming from. So basically on JVM we shouldn't be using cljs analyzer, but instead Clojure's resolve. Feel free to submit a PR for that. There's a helper `uix.lib/cljs-env?` to check if uix is running in cljs env or not.

**Comment by chrisetheridge** [comment]
Happy to! 🙂
